### ISSUE TITLE
ownership of repo

### ISSUE THREAD

**Issue by c-cube** [fxfactorial/ocaml-linenoise#9]
I'd like to have access to settings to update the docs (moving to gh-pages) and maybe setup CI. I also wonder if it makes sense to migrate the repository somewhere else (maybe ocaml-community but not sure if it's not too niche). What do you think @fxfactorial ?

**Comment by fxfactorial** [comment]
Sure! I defer to you.

**Comment by c-cube** [comment]
can you make me an admin on this repo, so I can change the settings wrt docs?

**Comment by fxfactorial** [comment]
I don't see the way to do admin though on repo?

**Comment by c-cube** [comment]
Good point, never noticed that (confirmed by https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account). I suppose it's simpler to directly transfer to ocaml-community then (which is a team so there can be several admins)

**Comment by fxfactorial** [comment]
Sounds good, will do that

**Comment by fxfactorial** [comment]
@c-cube I got an error from GitHub that I don't have permission to create repositories on ocaml-community

**Comment by c-cube** [comment]
I created a repo there and made you admin, let's see if it works?

**Comment by fxfactorial** [comment]
I got the same error, I think this is relevant: 

<img width="831" alt="screen shot 2018-11-19 at 12 55 26 pm" src="https://user-images.githubusercontent.com/3036816/48734514-7873b380-ebfa-11e8-8dd4-7e8369aa2d35.png">

so no write access might be the issue since this is error: 
<img width="721" alt="screen shot 2018-11-19 at 12 56 22 pm" src="https://user-images.githubusercontent.com/3036816/48734540-8c1f1a00-ebfa-11e8-9744-b3b80d8c424f.png">

**Comment by fxfactorial** [comment]
<img width="627" alt="screen shot 2018-11-19 at 1 08 22 pm" src="https://user-images.githubusercontent.com/3036816/48735079-33e91780-ebfc-11e8-9baf-2c2d6d592b9d.png">

Done!
